# Generated by Django 4.2.2 on 2025-05-15 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant_management',
            name='Event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event_app.event_management'),
        ),
        migrations.AddField(
            model_name='participant_management',
            name='sex',
            field=models.CharField(default='Not Specified', max_length=1),
        ),
        migrations.AddField(
            model_name='participant_management',
            name='university',
            field=models.CharField(default='Not Specified', max_length=200),
        ),
        migrations.AlterField(
            model_name='participant_management',
            name='name',
            field=models.CharField(default='Not Specified', max_length=150),
        ),
        migrations.AlterField(
            model_name='participant_management',
            name='phone_number',
            field=models.CharField(default='Not Specified', max_length=20),
        ),
    ]
