# Generated by Django 4.2.2 on 2025-05-19 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_participant_management_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event_management',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='participant_management',
            name='Event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.event_management'),
        ),
        migrations.AlterField(
            model_name='participant_management',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='participant_management',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='participant_management',
            name='sex',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='participant_management',
            name='university',
            field=models.CharField(max_length=200),
        ),
    ]
