# Generated by Django 5.2.1 on 2025-05-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0008_galleryimage_alter_event_management_is_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_management',
            name='location',
            field=models.CharField(choices=[('Nyarugenge Campus', 'Nyarugenge Campus: College of Science and Technology (CST)'), ('Gikondo Campus', 'Gikondo Campus: College of Business and Economics (CBE)'), ('Remera Campus', 'Remera Campus: College of Medicine and Health Sciences (CMHS)'), ('Huye Campus', 'Huye Campus'), ('Busogo Campus', 'Busogo Campus: College of Agriculture, Animal Sciences and Veterinary Medicine (CAVM)'), ('Nyagatare Campus', 'Nyagatare Campus'), ('Rukara Campus', 'Rukara Campus: College of Education (CE)'), ('Rusizi Campus', 'Rusizi Campus'), ('Rwamagana Campus', 'Rwamagana Campus'), ('Rubirizi Campus', 'Rubirizi Campus'), ('Nyamishaba Campus', 'Nyamishaba Campus'), ('Kicukiro Campus', 'Kicukiro Campus'), ('Kavumu Campus', 'Kavumu Campus'), ('Tumba Campus', 'Tumba Campus')], default='Nyarugenge Campus', max_length=100, verbose_name='Event Location (Campus)'),
        ),
    ]
