# Generated by Django 5.2.1 on 2025-05-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0009_alter_event_management_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant_management',
            name='university',
            field=models.CharField(choices=[('University of Rwanda', 'University of Rwanda'), ('Kigali Independent University (ULK)', 'Kigali Independent University (ULK)'), ('Adventist University of Central Africa (AUCA)', 'Adventist University of Central Africa (AUCA)'), ('Kigali Health Institute', 'Kigali Health Institute'), ('INES Ruhengeri', 'INES Ruhengeri'), ('Other', 'Other')], default='University of Rwanda', max_length=100, verbose_name='University'),
        ),
    ]
